{
 "title": "ActiveMQ日志(2.0&3.0)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "optdb", "label": "日志库", "query": "grafana-log-service-datasource" },
   {
    "name": "optintval",
    "label": "统计单位时长",
    "query": "1s,3s,10s,30s,1m,3m,10m,30m,1h,3h,6h,12h,1d"
   },
   { "name": "optintcnt", "label": "统计点数量", "query": "100,1000,10000,100000" },
   { "name": "source", "label": "IP", "query": "| select distinct source" },
   { "name": "hostname", "label": "机器名", "query": "| select distinct hostname" },
   { "name": "levelinfo", "label": "类型", "query": "| select distinct level" },
   { "name": "xtime01", "label": "响应时间下限", "query": "0" },
   { "name": "xtime02", "label": "响应时间上限", "query": "99999" }
  ]
 },
 "panels": [
  { "title": "全量统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "状态统计【$levelinfo】",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "repeat": "levelinfo",
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "query": "level:$levelinfo | select count(1) as cnt where  hostname in (${hostname})  and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))>=($__from/1000) and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))<=($__to/1000)",
     "target": "cnt",
     "type": "timeserie",
     "xcol": "single",
     "ycol": "cnt"
    }
   ]
  },
  {
   "title": "状态统计【$levelinfo】",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "query": "level:$levelinfo | select count(1) as cnt where  hostname in (${hostname})  and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))>=($__from/1000) and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))<=($__to/1000)",
     "target": "cnt",
     "type": "timeserie",
     "xcol": "single",
     "ycol": "cnt"
    }
   ]
  },
  {
   "title": "状态统计【$levelinfo】",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "query": "level:$levelinfo | select count(1) as cnt where  hostname in (${hostname})  and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))>=($__from/1000) and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))<=($__to/1000)",
     "target": "cnt",
     "type": "timeserie",
     "xcol": "single",
     "ycol": "cnt"
    }
   ]
  },
  {
   "title": "状态统计【$levelinfo】",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "query": "level:$levelinfo | select count(1) as cnt where  hostname in (${hostname})  and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))>=($__from/1000) and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))<=($__to/1000)",
     "target": "cnt",
     "type": "timeserie",
     "xcol": "single",
     "ycol": "cnt"
    }
   ]
  },
  {
   "title": "类型对比",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "* | select count(1) as cnt1, level, to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))- to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S')) % $$optintval as time where hostname in (${hostname}) and level in (${levelinfo})  and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))>=($__from/1000) and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))<=($__to/1000) group by time, level order by  time desc, level asc limit $optintcnt",
     "target": "level#:#cnt1",
     "type": "timeserie",
     "xcol": "time",
     "ycol": "level#:#cnt1"
    }
   ]
  },
  {
   "title": "机器对比",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "* | select count(1) as cnt1, hostname, to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S')) - to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S')) % $$optintval as time where hostname in (${hostname}) and level in (${levelinfo})  and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))>=($__from/1000) and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))<=($__to/1000) group by time, hostname order by  time desc, hostname asc limit $optintcnt",
     "target": "hostname#:#cnt1",
     "type": "timeserie",
     "xcol": "time",
     "ycol": "hostname#:#cnt1"
    }
   ]
  },
  {
   "title": "日志记录明细",
   "type": "table-old",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "* | select date, hostname, level, message where hostname in (${hostname}) and level in (${levelinfo})  and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))>=($__from/1000) and to_unixtime(date_parse(substr(date,1,19), '%Y-%m-%d %H:%i:%S'))<=($__to/1000) order by  date desc, level asc limit $optintcnt",
     "target": "date, hostname,level,message",
     "type": "timeserie",
     "ycol": "date, hostname,level,message"
    }
   ]
  }
 ]
}