{
 "title": "lmt主机监控",
 "description": "主机监控",
 "tags": [
  "StarsL",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   { "name": "buisnessline", "label": "产品线", "query": "lmt" },
   {
    "name": "appname",
    "label": "应用名称",
    "query": {
     "query": "label_values(node_exporter_build_info{env='$env',buisnessline='$buisnessline'},appname)"
    }
   },
   {
    "name": "modulename",
    "label": "模块名称",
    "query": {
     "query": "label_values(node_exporter_build_info{env='$env',buisnessline='$buisnessline',appname='$appname'},modulename)"
    }
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": {
     "query": "label_values(node_exporter_build_info{env='$env',buisnessline='$buisnessline',appname='$appname',modulename='$modulename'},hostname)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "系统运行时间",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{hostname=~\"$hostname\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU使用率（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{hostname=~\"$hostname\"} / (node_memory_MemTotal_bytes{hostname=~\"$hostname\"})))* 100"
    }
   ]
  },
  {
   "title": "当前打开的文件描述符",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filefd_allocated{hostname=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "根分区使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{hostname=~\"$hostname\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {hostname=~\"$hostname\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "最大分区($maxmount)使用率",
   "type": "singlestat",
   "description": "通过变量maxmount获取最大的分区。",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{hostname=~\"$hostname\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {hostname=~\"$hostname\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=~\"$hostname\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "$hostname", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "node" },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}-1m"
    },
    {
     "expr": "node_load5{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}-5m"
    },
    {
     "expr": "node_load15{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}-15m"
    }
   ]
  },
  {
   "title": "各分区可用空间",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {hostname=~\"$hostname\",fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{hostname=~\"$hostname\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{hostname=~\"$hostname\",fstype=~\"ext4|xfs\"})"
    },
    {}
   ]
  },
  {
   "title": "CPU使用率、磁盘每秒的I/O操作耗费时间（%）",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"system\"}[2m]))  by (hostname)",
     "legendFormat": "{{ hostname }}-System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"user\"}[2m]))  by (hostname)",
     "legendFormat": "{{ hostname }}-User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"iowait\"}[2m])) by (hostname)",
     "legendFormat": "{{ hostname }}-Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{hostname=~\"$hostname\"}[2m])",
     "legendFormat": "{{ hostname }}-{{device}}_每秒I/O操作%"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=~\"$hostname\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{hostname=~\"$hostname\"} - node_memory_MemAvailable_bytes{hostname=~\"$hostname\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{hostname=~\"$hostname\"}",
     "legendFormat": "可用"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{hostname=~\"$hostname\"}[2m])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{hostname=~\"$hostname\"}[2m])",
     "legendFormat": "{{ hostname }}-{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘读写容量大小",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{hostname=~\"$hostname\"}[2m])",
     "legendFormat": "{{ hostname }}-{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{hostname=~\"$hostname\"}[2m])",
     "legendFormat": "{{ hostname }}-{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘IO读写时间",
   "type": "graph",
   "description": "Read time ms 每个磁盘分区读操作花费的秒数\n\nWrite time ms 每个磁盘分区写操作花费的秒数\n\nIO time ms 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted 每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{hostname=~\"$hostname\"}[2m])",
     "legendFormat": "{{ hostname }}-{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{hostname=~\"$hostname\"}[2m])",
     "legendFormat": "{{ hostname }}-{{device}}_写入"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{hostname=~\"$hostname\",device!~'tap.*'}[5m])*8",
     "legendFormat": "{{ hostname }}-{{device}}_in入流量"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{hostname=~\"$hostname\",device!~'tap.*'}[5m])*8",
     "legendFormat": "{{ hostname }}-{{device}}_out出流量"
    }
   ]
  },
  {
   "title": "TCP 连接情况",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}-ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}-TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{ hostname }}-ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{hostname=~\"$hostname\"}[1m])",
     "legendFormat": "{{ hostname }}-PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}-TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}-TCP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{hostname=~\"$hostname\"}-node_netstat_Tcp_CurrEstab{hostname=~\"$hostname\"}",
     "legendFormat": "{{instance}}-非正常连接"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{hostname=~\"$hostname\"} / node_memory_MemTotal_bytes{hostname=~\"$hostname\"}))* 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100-avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"idle\"}[5m]) * 100) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}