{
 "title": "skywalking",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "appid",
    "label": "服务",
    "query": {
     "query": "label_values(skywalking_total,ApplyName)"
    }
   },
   {
    "name": "uri",
    "label": "uri",
    "query": "label_values(skywalking_total{ApplyName=~\"$appid\"},InstanceName)"
   }
  ]
 },
 "panels": [
  { "title": "服务层", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "调用总数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "skywalking_total{valuetype=\"service\",ApplyName=~\"$appid\"}",
     "legendFormat": "{{ApplyName}}"
    }
   ]
  },
  {
   "title": "失败数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "skywalking_total{valuetype=\"service\",ApplyName=~\"$appid\"}-skywalking_match{valuetype=\"service\",ApplyName=~\"$appid\"}",
     "legendFormat": "{{ApplyName}}"
    }
   ]
  },
  {
   "title": "成功率",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "skywalking_percentage{valuetype=\"service\",ApplyName=~\"$appid\"}/100",
     "legendFormat": "{{ApplyName}}"
    }
   ]
  },
  {
   "title": "调用耗时",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "skywalking_avg{valuetype=\"service\",ApplyName=~\"$appid\"}",
     "legendFormat": "{{ApplyName}}-avg"
    },
    {
     "expr": "skywalking_p50{valuetype=\"service\",ApplyName=~\"$appid\"}",
     "legendFormat": "{{ApplyName}}-p50"
    },
    {
     "expr": "skywalking_p75{valuetype=\"service\",ApplyName=~\"$appid\"}",
     "legendFormat": "{{ApplyName}}-p75"
    },
    {
     "expr": "skywalking_p90{valuetype=\"service\",ApplyName=~\"$appid\"}",
     "legendFormat": "{{ApplyName}}-p90"
    },
    {
     "expr": "skywalking_p99{valuetype=\"service\",ApplyName=~\"$appid\"}",
     "legendFormat": "{{ApplyName}}-p99"
    }
   ]
  },
  { "title": "URI层", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "uri调用详情",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "skywalking_total{valuetype=\"endpoint\",ApplyName=~\"$appid\",InstanceName=~\"$uri\"}",
     "legendFormat": "{{ApplyName}}-{{InstanceName}}"
    }
   ]
  },
  {
   "title": "uri调用失败详情",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "skywalking_total{valuetype=\"endpoint\",ApplyName=~\"$appid\",InstanceName=~\"$uri\"}-skywalking_match{valuetype=\"endpoint\",ApplyName=~\"$appid\",InstanceName=~\"$uri\"}",
     "legendFormat": "{{ApplyName}}-{{InstanceName}}"
    }
   ]
  },
  {
   "title": "uri成功率",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "skywalking_percentage{valuetype=\"endpoint\",ApplyName=~\"$appid\",InstanceName=~\"$uri\"}/100",
     "legendFormat": "{{ApplyName}}-{{InstanceName}}"
    }
   ]
  },
  {
   "title": "调用耗时",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "skywalking_avg{valuetype=\"endpoint\",ApplyName=~\"$appid\",InstanceName=~\"$uri\"}",
     "legendFormat": "{{ApplyName}}-{{InstanceName}}-avg"
    },
    {
     "expr": "skywalking_p50{valuetype=\"endpoint\",ApplyName=~\"$appid\",InstanceName=~\"$uri\"}",
     "legendFormat": "{{ApplyName}}-{{InstanceName}}-p50"
    },
    {
     "expr": "skywalking_p75{valuetype=\"endpoint\",ApplyName=~\"$appid\",InstanceName=~\"$uri\"}",
     "legendFormat": "{{ApplyName}}-{{InstanceName}}-p75"
    },
    {
     "expr": "skywalking_p90{valuetype=\"endpoint\",ApplyName=~\"$appid\",InstanceName=~\"$uri\"}",
     "legendFormat": "{{ApplyName}}-{{InstanceName}}-p90"
    },
    {
     "expr": "skywalking_p99{valuetype=\"endpoint\",ApplyName=~\"$appid\",InstanceName=~\"$uri\"}",
     "legendFormat": "{{ApplyName}}-{{InstanceName}}-p99"
    }
   ]
  }
 ]
}